# Check if NumPy is installed

In [5]:
import numpy
print(numpy.__version__)

1.23.5


### If not installed, install with
# pip install numpy

# NumPy array

In [17]:
import numpy as np
l = [10, 20, 30, 40] # list
arr = np.array(l) # create array object

print(type(l)) # list
print(type(arr)) # numpy.ndarray

print(arr)

<class 'list'>
<class 'numpy.ndarray'>
[10 20 30 40]


In [21]:
l = [[10, 20, 50],[30, 40, 50]] # list
arr = np.array(l)

print(arr)

[[10 20 50]
 [30 40 50]]


# Check Dimension

In [25]:
a = np.array(10) # 0D
b = np.array([20]) # 1D
c = np.array([20, 30]) # 1D
d = np.array([[20, 30], [40, 50]]) # 2D

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
1
2


# Higher dimentional array

In [35]:
arr = np.array([1, 2, 3, 4], ndmin = 3)

print(arr.ndim)
print(arr)

3
[[[1 2 3 4]]]


### Accessing index

In [37]:
arr = np.array([10, 20, 30, 40])

print(arr[2])

30


In [40]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

# access 0,2 index
print(arr[0, 2])

# negative index
print(arr[1, -2])

30
50


# Slicing

In [45]:
arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[2 : 4])
print(arr[-4 : -2])
print(arr[2 : -2])
print(arr[2 : 1])

[30 40]
[30 40]
[30 40]
[]


In [47]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# step value is 2
print(arr[1 : -1])
print(arr[1 : -1 : 2])

[20 30 40 50 60 70 80]
[20 40 60 80]
